import { Request, Response } from "express";
import Task from "../models/task.model";
import CompletedTask from "../models/completedTask.model";
import * as taskService from '../services/taskService';
import * as userClient from '../clients/userClient';

export const createTask = async (req: Request, res: Response): Promise<void> => {
  try {
    const { taskName, dueDate, priority, category, userEmail, description, isCompleted } = req.body;

    // taskId will be auto-generated by the model (UUID). Do not accept client-provided taskId.
    const task = new Task({
      taskName,
      dueDate,
      priority,
      category,
      userEmail,
      description,
      isCompleted,
    });

    await task.save();
    res.status(201).json({ message: "Task created successfully", task });
  } catch (error) {
    console.error("Error creating task:", error);
    res.status(500).json({ message: "Server error" });
  }
};

export const getAllTasks = async (req: Request, res: Response): Promise<void> => {
  try {
    const tasks = await Task.find().sort({ createdAt: -1 });
    res.status(200).json(tasks);
  } catch (error) {
    res.status(500).json({ message: "Server error" });
  }
};


export const getPendingTasks = async (req: Request, res: Response): Promise<void> => {
  try {
    const { status } = req.params;
    if (status == "pending") {
        const pendingTasks = await Task.find({ status: "pending" }).sort({ createdAt: -1 });

        if (!pendingTasks || pendingTasks.length === 0) {
          res.status(404).json({ message: "No pending tasks found" });
          return;
        }
        res.status(200).json(pendingTasks);
    } else {
        const tasks = await Task.find().sort({ createdAt: -1 });
      res.status(200).json(tasks);
    }
      } catch (error) {
    res.status(500).json({ message: "Server error" });
  }
};


export const getTaskbyId = async (req: Request, res: Response): Promise<void> => {
  try {
    console.log("Fetching task by ID:", req.params);
    const { id } = req.params;
    const task = await Task.findOne({ taskId: id });
    if (!task) {
      res.status(404).json({ message: 'Task not found' });
      return;
    }
    res.json(task);
  } catch (error) {
    res.status(500).json({ message: "Server error" });
  }
};


export const updateTask = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const updateData = req.body;

    const updatedTask = await Task.findOneAndUpdate({ taskId: id }, updateData, {
      new: true,
      runValidators: true,
    });

    if (!updatedTask) {
      res.status(404).json({ message: "Task not found" });
      return;
    }

    res.status(200).json(updatedTask);
  } catch (error) {
    console.error("Error updating task:", error);
    res.status(500).json({ message: "Server error" });
  }
};

export const deleteTask = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;

    const deletedTask = await Task.findOneAndDelete({ taskId: id });

    if (!deletedTask) {
      res.status(404).json({ message: "Task not found" });
      return;
    }

    res.status(200).json({ message: "Task deleted successfully", task: deletedTask });
  } catch (error) {
    console.error("Error deleting task:", error);
    res.status(500).json({ message: "Server error" });
  }
};

export const markTaskComplete = async (req: Request, res: Response): Promise<void> => {
  try {
    const { taskId, userEmail } = req.body;

    if (!taskId || !userEmail) {
      res.status(400).json({ message: 'taskId and userEmail are required' });
      return;
    }

    const result = await taskService.completeTask(taskId);

    try {
      await userClient.addReward(userEmail, result.points);
    } catch (err) {
      console.error('Failed to add reward to user:', (err as any).message || err);
    }

    res.status(200).json({ message: 'Task completed and moved to completed tasks', points: result.points });
  } catch (error) {
    console.error("Error completing task:", error);
    res.status(500).json({ message: "Server error" });
  }
};